http:
  port: "8081"
  private: 
    port: "8091"
https:
  port: "8082"
api: 
  id: "2616784"
system:
    protocol: "HTTP"
    host: "does-not-exist.cloudhub.io"
    port: "80"
    basePath: "/"
    connectionIdleTimeout: "10000"
    responseTimeout: "5000"
sap:
    protocol: "HTTPS"
    user: "SOA_GEOCALL"
    host: "----"
    port: "443"
    address: "https://------/sap/bc/srt/rfc/sap/z_wfm_geocall_esito_allegati/300/zwfm_geocall_esito_allegati/zwfm_geocall_esito_allegati"
    uri: "/sap/bc/srt/rfc/sap/z_wfm_geocall_esito_allegati/300/zwfm_geocall_esito_allegati/zwfm_geocall_esito_allegati"
nextGen:
    protocol: "HTTPS"
    host: "-----------"
    port: "443"
    basePath: "/"
    connectionIdleTimeout: "10000"
    responseTimeout: "60000" 
    services:
      outComeAttachments: "/veritaswfm/api/r1/outcome-attachments/{idAllegato}"
mq:
  host: "https://mq-eu-central-1.eu1.anypoint.mulesoft.com/api/v1/organizations/cc2a9e24-8e94-4042-8c32-c19a2189dc8d/environments/6f21d59d-13ab-4bd5-aedd-756b16c03aa1"
  client_id: "62f153b9e4c94a4c9c65325b75ab6b0d"
  esito-allegati: "PROD-QUEUE-allegati-geocall-lista"
  max-local-message-geoCallProc: "8"
store:
  expirationInterval: "1"
log:
  level: "DEBUG"
 